package cn.com.flaginfo.platform.registered.mybatis.entity;

import cn.com.flaginfo.platform.registered.mybatis.base.BaseEntity;

public class ApplicationService extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_service.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_service.app_encoding_key
     *
     * @mbggenerated
     */
    private String appEncodingKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_service.callback_url
     *
     * @mbggenerated
     */
    private String callbackUrl;





    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_service.app_key
     *
     * @return the value of application_service.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_service.app_key
     *
     * @param appKey the value for application_service.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_service.app_encoding_key
     *
     * @return the value of application_service.app_encoding_key
     *
     * @mbggenerated
     */
    public String getAppEncodingKey() {
        return appEncodingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_service.app_encoding_key
     *
     * @param appEncodingKey the value for application_service.app_encoding_key
     *
     * @mbggenerated
     */
    public void setAppEncodingKey(String appEncodingKey) {
        this.appEncodingKey = appEncodingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_service.callback_url
     *
     * @return the value of application_service.callback_url
     *
     * @mbggenerated
     */
    public String getCallbackUrl() {
        return callbackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_service.callback_url
     *
     * @param callbackUrl the value for application_service.callback_url
     *
     * @mbggenerated
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

}