package cn.com.flaginfo.platform.registered.mybatis.entity;

import cn.com.flaginfo.platform.registered.mybatis.base.BaseEntity;

public class EventFailureRecord extends BaseEntity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.app_id
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.event_type
     *
     * @mbggenerated
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.content
     *
     * @mbggenerated
     */
    private String content;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.app_id
     *
     * @return the value of event_failure_record.app_id
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.app_id
     *
     * @param appId the value for event_failure_record.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.app_key
     *
     * @return the value of event_failure_record.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.app_key
     *
     * @param appKey the value for event_failure_record.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.event_type
     *
     * @return the value of event_failure_record.event_type
     *
     * @mbggenerated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.event_type
     *
     * @param eventType the value for event_failure_record.event_type
     *
     * @mbggenerated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.content
     *
     * @return the value of event_failure_record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.content
     *
     * @param content the value for event_failure_record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }
}