package cn.com.flaginfo.platform.registered.mybatis.entity;

import cn.com.flaginfo.platform.registered.mybatis.base.BaseEntity;

public class EventFailureRecord extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.app_id
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_failure_record.modify_date
     *
     * @mbggenerated
     */
    private String modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.id
     *
     * @return the value of event_failure_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.id
     *
     * @param id the value for event_failure_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.app_id
     *
     * @return the value of event_failure_record.app_id
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.app_id
     *
     * @param appId the value for event_failure_record.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.status
     *
     * @return the value of event_failure_record.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.status
     *
     * @param status the value for event_failure_record.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.content
     *
     * @return the value of event_failure_record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.content
     *
     * @param content the value for event_failure_record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.create_date
     *
     * @return the value of event_failure_record.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.create_date
     *
     * @param createDate the value for event_failure_record.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_failure_record.modify_date
     *
     * @return the value of event_failure_record.modify_date
     *
     * @mbggenerated
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_failure_record.modify_date
     *
     * @param modifyDate the value for event_failure_record.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate;
    }
}