package cn.com.flaginfo.platform.registered.mybatis.mapper;

import cn.com.flaginfo.platform.registered.mybatis.entity.ApplicationService;
import cn.com.flaginfo.platform.registered.mybatis.entity.ApplicationServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ApplicationServiceMapper extends BaseMapper<ApplicationService,ApplicationServiceExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    int countByExample(ApplicationServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    int deleteByExample(ApplicationServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    int insert(ApplicationService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    int insertSelective(ApplicationService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    List<ApplicationService> selectByExampleWithRowbounds(ApplicationServiceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    List<ApplicationService> selectByExample(ApplicationServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApplicationService record, @Param("example") ApplicationServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_service
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApplicationService record, @Param("example") ApplicationServiceExample example);

    /**
     *
     */
    List<ApplicationService> getAppInfoByEventType(@Param("record") ApplicationService record);
}