package cn.com.flaginfo.platform.registered.mybatis.mapper;

import cn.com.flaginfo.platform.registered.mybatis.entity.RegisterEvent;
import cn.com.flaginfo.platform.registered.mybatis.entity.RegisterEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RegisterEventMapper extends BaseMapper<RegisterEvent,RegisterEventExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    int countByExample(RegisterEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    int deleteByExample(RegisterEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    int insert(RegisterEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    int insertSelective(RegisterEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    List<RegisterEvent> selectByExampleWithRowbounds(RegisterEventExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    List<RegisterEvent> selectByExample(RegisterEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RegisterEvent record, @Param("example") RegisterEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_event
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RegisterEvent record, @Param("example") RegisterEventExample example);
}